### ISSUE TITLE
Support setting MapToOutput xorg.conf.d

### ISSUE THREAD

**Issue by christophgysin** [linuxwacom/xf86-input-wacom#106]
For screens with builtin wacom devices, it would be nice to be able to configure the driver to always map to that output.

It seems that currently the only way to map a device to an output is using xsetwacom.

**Comment by whot** [comment]
yeah, the basic reason for that is that an "output" is a bit more complex and at the time we parse the xorg.conf settings we may not have all outputs available, let alone know the size of them. it's done in xsetwacom because that way it can be run  by the user whenever the output configuration changes (e.g. monitor plugged/unplugged). We simply don't have the infrastructure anymore in the input drivers to keep up with display sizes. This used to work 2 decades ago but only because you had to specify the screens in the xorg.conf as well and hotplugging wasn't a thing.
