### ISSUE TITLE
ARM64 Support?

### ISSUE THREAD

**Issue by mrwesleycrusher** [linuxwacom/xf86-input-wacom#121]
Hi,
I don't see anything that would prevent xf86-input-wacom from supporting ARM64 based devices, but from what I have seen I haven't seen anything confirming that it will work neither.

Will xf86-input-wacom work on ARM64?

**Comment by jigpu** [comment]
It should work just fine since there's nothing architecture-specific in the driver. It works on the Pi (which is ARM32, I believe) and there's nothing special we did for that. There's a small chance you'll have some trouble with building the driver, but it should be pretty straightforward to fix if that does happen.
