### ISSUE TITLE
wacom intuos pro M rotation issue

### ISSUE THREAD

**Issue by pascalfleury** [linuxwacom/xf86-input-wacom#130]
I have just gotten my Intuos Pro M and used it in Krita. Being left-handed, I have set it up as 'Upside-Down' so that the button are on the right.

The system settings (at least in KDE) have an option to rotate the input 180 degrees so that this setup works with the stylus. 

The Intuos Pro M though can also work as a touch pad (a big one, I know), and this works but the rotation is not applied to that part of the tablet's input. So if I go with the stylus to the top left of the tablet, the pointers gets to the top left. When I do the same with the fingers, it gets to the bottom right.

Can the orientation setting also be applied to the touchpad-aspect of the tablet ?

**Comment by whot** [comment]
Most likely the issue here is that the touchpad part of the device is handled by the xf86-input-libinput driver. That doesn't support rotation (well, it does but only if it *also* handles the tablet). So your options are either switch to the xf86-input-libinput driver for the tablet (removing the wacom driver is enough) or switching the touchpad part of the tablet to the wacom driver. You can do this by creating this file (and parent folders, if necessary)
```
$ cat /etc/X11/xorg.conf.d/99-override-wacom-touchpads.conf
Section "InputClass"
        Identifier "force wacom for touchpads"
        MatchDriver "libinput"
        MatchIsTouchpad "true"
        Driver "wacom"
EndSection
```
If you have another touchpad, you should add a `MatchProduct` as well to only match the intuos (see `man xorg.conf` for details). Restarting X and the rotation property should be available for that device.
