### ISSUE TITLE
xsetwacom - displaytoggle no longer supported

### ISSUE THREAD

**Issue by Pshemas** [linuxwacom/xf86-input-wacom#16]
I'm not sure whether this covers xsetwacom as well, but as I haven't found other place...
Following Arch wiki I've been trying to set up keys for my tablet (damn, such a shame there's no gui tool that would store configs, but I digress). I had my hopes up when I've seen "displaytoggle" argument that coud have been assigned to the key - would be awesome for my multimonitor setup. But when I try it  I get:

> The "displaytoggle" keyword is not supported anymore and will be ignored.

Is there any kind of equivalent for it? At the very least what is the way to assign mapping of specific monitor to specific key. Atm I have to use :

>xsetwacom set "Wacom Intuos S Pen stylus" maptooutput 2560x1440+0+0

in the terminal each time I connect my tablet.

**Comment by jigpu** [comment]
Replicating the old "displaytoggle" functionality can be done by defining a keyboard shortcut that runs a script. For instance, you can have the following script run whenever "Super+N" is pressed. The "next" keyword will cause the pen to be cycled through each output and the entire desktop every time the script is run. You can, of course, replace it with "2560x1440+0+0" or anything else if you would prefer. 

If your desktop does not offer a way to run a command in response to a keyboard shortcut, you can make use of the "[xbindkeys](http://www.nongnu.org/xbindkeys/xbindkeys.html)" daemon. You can then

~~~
#!/bin/sh
xsetwacom set "Wacom Intuos S Pen stylus" maptooutput next
~~~

You can also configure your tablet to send the keyboard shortcut so that you don't have to reach over to the keyboard. Getting the configuration to apply every time you connect your tablet is tricky, however. Normally you'd want to use an "xorg.conf.d" file to define the setting, but the driver doesn't yet support complicated xsetwacom-style button mapping strings through these files.

An alternative would be to run a daemon which waits for tablets to be plugged in and applies some configuration. I've written such a daemon, which you can find [here](https://gist.github.com/jigpu/eccc75b1096a9f6ac898). You'll need to have your desktop run the script on startup, but that shouldn't be too difficult.

Please let me know if you are able to get this working or if you run into any problems.
