### ISSUE TITLE
Assigning scroll?

### ISSUE THREAD

**Issue by Pshemas** [linuxwacom/xf86-input-wacom#34]
It seems Gnome is the only DE that supports configuration of Wacom devices almost fully. But it seems there's no way to configure scrollbars / wheels with it (and it does not take into account monitor rotations correctly - but I understand it is Gnome project's thing to fix).
Is there a way to configure those scrolls through command line?

**Comment by jigpu** [comment]
The default behavior of our X driver is to map the wheels and strips to scrolling. If you can disable GNOME's tablet integration, it should be possible to restore the original behavior. In the past, this could be done by running the following command. Unfortunately, it hasn't been possible to disable the integration for the past few GNOME releases (the integration became too tight). If you want to try though, the following command used to work. Be sure to run it from within an Xorg session since you can't use xsetwacom from Wayland:
~~~
gsettings set org.gnome.settings-daemon.plugins.gsdwacom active false
~~~
Afterwards, you can see if this had any effect by then running the following commands to ensure the wheel function is reset to its default (use 'stripleft' instead of 'abswheel' if your device uses a touchstrip). If you were able to disable the integration then the terminal and other documents should scroll when you use the wheel.
~~~
xsetwacom set <PAD_ID> abswheelup button +4
xsetwacom set <PAD_ID> abswheeldown button +5
~~~
Really though, you should file an issue at https://gitlab.gnome.org/GNOME/gnome-control-center/issues to let them know that you aren't able to use your wheels for scrolling. A number of people have requested the feature, but I'm not sure the GNOME developers are aware just how important it is for some people.
