### ISSUE TITLE
Pad button actions on Artz II (UD-1212-R) serial tablet

### ISSUE THREAD

**Issue by pdaoust** [linuxwacom/xf86-input-wacom#81]
I was delighted to discover that my old serial Artz II tablet works beautifully on Ubuntu 19.04 without any special work necessary beyond running `inputattach` (and upping the threshold for the very old and flaky stylus).

I was wondering: the pad itself isn't listed as a device; is it possible to capture button strip events and turn them into actions? `xinput test` shows no events are actually triggered when I tap them with the stylus, but I don't know if that's due to lack of support at the driver level or some config that needs to be twiddled.

Here's what the button strip looks like:

![](https://i.imgur.com/dxl5dxY.jpg)

**Comment by jigpu** [comment]
The ArtZ II predates my involvement quite a bit, so I'm not particularly familiar with the hardware. My assumption is that the strip on that particular tablet is entirely software driven, rather than a real hardware feature. I'm not aware of any software for Linux that would let you make use of the strip. Software could probably be developed, but given how old the tablet is, its not something that we're all that interested in working on.
